remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"
title: CS-571
description: CS-571 Building User Interfaces, Fall 2021, Professor Yuhang Zhao, University of Wisconsin--Madison
search_enabled: true