remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
title: CS-571 
subtitle: "CS-571 Building User Interfaces"
author: Professor Zhao
description: "CS-571 Building User Interfaces, Fall 2021, Professor Zhao, University of Wisconsin--Madison"
search_enabled: true
footer_content: "Copyright &copy 2021 Yuhang Zhao"
header_pages:
  - index.md
  - schedule.md
  - syllabus.md

